name: Test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  execute-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: |
          /bin/bash -x run.sh install
      - name: Configure git user
        run: |
          git config --global user.email "rodrigocesar@gmail.com"
          git config --global user.name "Rodrigo Cesar da Silva"
      - name: Run tests
        run: |
          /bin/bash -x run.sh test



